# Site
repository: ibLeDy/ibledy.github.io
favicon: images/favicon.ico

# Personal info
name: Iago Alonso
title: Self-Taught Python Developer and Computer Technician
email: deejaynof@gmail.com
# phone: Your phone number (optional)
# website: iagoalonso.xyz

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: DeejayNof
github_username:  ibLeDy
stackoverflow_username: "10817439"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: iago-alonso
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: DeejayNof
# orcid_username: 0000-0003-0975-8590

# Additional icon links
additional_links:
- title: Gitlab link
  icon: fa-gitlab
  url: https://gitlab.com/bLeDy
- title: Hackerrank link
  icon: fa-hackerrank
  url: https://hackerrank.com/deejaynof
# - title: Keybase link
#   icon: fa-keybase
#   url: https://keybase.io/bledy
# - title: DEV link
#   icon: fa-dev
#   url: https://dev.to/ibledy
# - title: freeCodeCamp link
#   icon: fa-free-code-camp
#   url: https://www.freecodecamp.org/bledy

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I started with software pretty early, configuring each program to the maximum,
  discovering how they worked and testing as many new applications as I could.
  Since in my family there was always a shortage of devices with which to risk
  taking apart, hardware had to wait a bit.

  As soon as i had any opportunity, i disassembled, reassembled and began discovering
  the world of hardware, learning how computers worked and how to modify,
  repair and configure almost every part of a modern PC.

  I’ve chosen Python as my main programming language because I think it is the most
  complete tool that enables learning with the least syntactic barrier.
  That being said, I enjoy learning the latest and greatest technologies and frameworks,
  although I'm mainly focused on backend.

  I was always passionate about computers and I have a non-common ease of understanding
  of how they work and it's most complex concepts, enabling me to learn quickly and with
  high standards. I also taught myself about music production and video editing
  (motion graphics and video production/postproduction).

# Projects Section
projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  - I love learning and improving.
  - I learn quickly and I'm open to every technology/framework/language.
  - I like to do a lot of research and I'm used to dealing with technical documentation.

# Footer
# footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
